// <auto-generated />
using Bood.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bood.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260701044310_UpdateServiceImages")]
    partial class UpdateServiceImages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Bood.Api.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "$2a$11$ExampleHashPlaceholderForAdmin123",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("Bood.Api.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 0,
                            Description = "Comprehensive management for 5-star properties.",
                            ImageUrl = "https://images.unsplash.com/photo-1542314831-c6a4d27ce66b?auto=format&fit=crop&w=600&q=80",
                            Title = "Luxury Hotel Operations"
                        },
                        new
                        {
                            Id = 2,
                            Category = 0,
                            Description = "Seamless execution of high-end events.",
                            ImageUrl = "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?auto=format&fit=crop&w=600&q=80",
                            Title = "Event & Banquet Services"
                        },
                        new
                        {
                            Id = 3,
                            Category = 0,
                            Description = "Premium guest services and personalized experiences.",
                            ImageUrl = "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=600&q=80",
                            Title = "Concierge Excellence"
                        },
                        new
                        {
                            Id = 4,
                            Category = 0,
                            Description = "Culinary operations for world-class restaurants.",
                            ImageUrl = "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=600&q=80",
                            Title = "Fine Dining Management"
                        },
                        new
                        {
                            Id = 5,
                            Category = 0,
                            Description = "Tranquil operations for luxury spa facilities.",
                            ImageUrl = "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=600&q=80",
                            Title = "Spa & Wellness"
                        },
                        new
                        {
                            Id = 6,
                            Category = 0,
                            Description = "Secure and efficient vehicle management.",
                            ImageUrl = "https://images.unsplash.com/photo-1513337965427-466a9e1e57c1?auto=format&fit=crop&w=600&q=80",
                            Title = "Valet & Parking"
                        },
                        new
                        {
                            Id = 7,
                            Category = 1,
                            Description = "Intensive sanitation for commercial spaces.",
                            ImageUrl = "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=600&q=80",
                            Title = "Deep Cleaning"
                        },
                        new
                        {
                            Id = 8,
                            Category = 1,
                            Description = "Routine maintenance for spotless environments.",
                            ImageUrl = "https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?auto=format&fit=crop&w=600&q=80",
                            Title = "Daily Janitorial"
                        },
                        new
                        {
                            Id = 9,
                            Category = 1,
                            Description = "Streak-free exterior and interior glass cleaning.",
                            ImageUrl = "https://images.unsplash.com/photo-1558227097-440263f91572?auto=format&fit=crop&w=600&q=80",
                            Title = "Window & Glass"
                        },
                        new
                        {
                            Id = 10,
                            Category = 1,
                            Description = "Deep extraction and fabric protection.",
                            ImageUrl = "https://images.unsplash.com/photo-1628177142898-93e46e46248d?auto=format&fit=crop&w=600&q=80",
                            Title = "Carpet Restoration"
                        },
                        new
                        {
                            Id = 11,
                            Category = 1,
                            Description = "Heavy-duty cleaning for factories and warehouses.",
                            ImageUrl = "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?auto=format&fit=crop&w=600&q=80",
                            Title = "Industrial Sanitation"
                        },
                        new
                        {
                            Id = 12,
                            Category = 1,
                            Description = "Removing debris and dust after renovations.",
                            ImageUrl = "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=600&q=80",
                            Title = "Post-Construction"
                        },
                        new
                        {
                            Id = 13,
                            Category = 2,
                            Description = "Scheduled checks to ensure uninterrupted operations.",
                            ImageUrl = "https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&w=600&q=80",
                            Title = "Preventative Maintenance"
                        },
                        new
                        {
                            Id = 14,
                            Category = 2,
                            Description = "Heating, ventilation, and air conditioning care.",
                            ImageUrl = "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&w=600&q=80",
                            Title = "HVAC Systems"
                        },
                        new
                        {
                            Id = 15,
                            Category = 2,
                            Description = "Safe and reliable power system management.",
                            ImageUrl = "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=600&q=80",
                            Title = "Electrical Services"
                        },
                        new
                        {
                            Id = 16,
                            Category = 2,
                            Description = "Comprehensive water system maintenance.",
                            ImageUrl = "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=600&q=80",
                            Title = "Plumbing Solutions"
                        },
                        new
                        {
                            Id = 17,
                            Category = 2,
                            Description = "Ensuring safe and smooth vertical transport.",
                            ImageUrl = "https://images.unsplash.com/photo-1507122119958-fb45731ed099?auto=format&fit=crop&w=600&q=80",
                            Title = "Elevator Maintenance"
                        },
                        new
                        {
                            Id = 18,
                            Category = 2,
                            Description = "Immediate response for critical infrastructure.",
                            ImageUrl = "https://images.unsplash.com/photo-1599305090598-fe179d501227?auto=format&fit=crop&w=600&q=80",
                            Title = "24/7 Emergency Repairs"
                        },
                        new
                        {
                            Id = 19,
                            Category = 3,
                            Description = "Creating beautiful and sustainable outdoor spaces.",
                            ImageUrl = "https://images.unsplash.com/photo-1558904541-efa843a96f09?auto=format&fit=crop&w=600&q=80",
                            Title = "Landscape Design"
                        },
                        new
                        {
                            Id = 20,
                            Category = 3,
                            Description = "Regular mowing, trimming, and fertilization.",
                            ImageUrl = "https://images.unsplash.com/photo-1584738766473-61c083514bf4?auto=format&fit=crop&w=600&q=80",
                            Title = "Lawn Care"
                        },
                        new
                        {
                            Id = 21,
                            Category = 3,
                            Description = "Efficient water management for greenery.",
                            ImageUrl = "https://images.unsplash.com/photo-1583091151604-d7d8e6302e1c?auto=format&fit=crop&w=600&q=80",
                            Title = "Irrigation Systems"
                        },
                        new
                        {
                            Id = 22,
                            Category = 3,
                            Description = "Patios, walkways, and retaining walls.",
                            ImageUrl = "https://images.unsplash.com/photo-1563204907-2a445b597cd9?auto=format&fit=crop&w=600&q=80",
                            Title = "Hardscaping"
                        },
                        new
                        {
                            Id = 23,
                            Category = 3,
                            Description = "Pruning, removal, and health assessments.",
                            ImageUrl = "https://images.unsplash.com/photo-1524334228333-0f6db392f8a1?auto=format&fit=crop&w=600&q=80",
                            Title = "Tree Care"
                        },
                        new
                        {
                            Id = 24,
                            Category = 3,
                            Description = "Vibrant floral displays year-round.",
                            ImageUrl = "https://images.unsplash.com/photo-1416879573089-1ea2df6cc587?auto=format&fit=crop&w=600&q=80",
                            Title = "Seasonal Planting"
                        },
                        new
                        {
                            Id = 25,
                            Category = 4,
                            Description = "Professional first impressions for your business.",
                            ImageUrl = "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=600&q=80",
                            Title = "Reception & Front Desk"
                        },
                        new
                        {
                            Id = 26,
                            Category = 4,
                            Description = "Efficient handling of incoming and outgoing post.",
                            ImageUrl = "https://images.unsplash.com/photo-1580922881267-31c3c97e74dc?auto=format&fit=crop&w=600&q=80",
                            Title = "Mailroom Operations"
                        },
                        new
                        {
                            Id = 27,
                            Category = 4,
                            Description = "Ensuring smooth day-to-day administrative tasks.",
                            ImageUrl = "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=600&q=80",
                            Title = "Office Management"
                        },
                        new
                        {
                            Id = 28,
                            Category = 4,
                            Description = "Trained guards to protect your assets.",
                            ImageUrl = "https://images.unsplash.com/photo-1506476104332-f1559902bebc?auto=format&fit=crop&w=600&q=80",
                            Title = "Security Personnel"
                        },
                        new
                        {
                            Id = 29,
                            Category = 4,
                            Description = "Safe and effective eradication programs.",
                            ImageUrl = "https://images.unsplash.com/photo-1596700868128-4ce67a740dc8?auto=format&fit=crop&w=600&q=80",
                            Title = "Pest Control"
                        },
                        new
                        {
                            Id = 30,
                            Category = 4,
                            Description = "Sustainable disposal and recycling solutions.",
                            ImageUrl = "https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?auto=format&fit=crop&w=600&q=80",
                            Title = "Waste Management"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
