// <auto-generated />
using Bood.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bood.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260703040202_AddBilingualFields")]
    partial class AddBilingualFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Bood.Api.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "admin123",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("Bood.Api.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescriptionAr")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 0,
                            DescriptionAr = "إدارة شاملة للمنشآت ذات الخمس نجوم لضمان أعلى معايير الجودة.",
                            DescriptionEn = "Comprehensive management for 5-star properties.",
                            ImageUrl = "/assets/bood-design/images/bood-service-1.jpg",
                            TitleAr = "إدارة عمليات الفنادق الفاخرة",
                            TitleEn = "Luxury Hotel Operations"
                        },
                        new
                        {
                            Id = 2,
                            Category = 0,
                            DescriptionAr = "تنفيذ سلس واحترافي للفعاليات والمناسبات الراقية.",
                            DescriptionEn = "Seamless execution of high-end events.",
                            ImageUrl = "/assets/bood-design/images/bood-service-3.jpg",
                            TitleAr = "خدمات الفعاليات والمناسبات",
                            TitleEn = "Event & Banquet Services"
                        },
                        new
                        {
                            Id = 3,
                            Category = 0,
                            DescriptionAr = "خدمات ضيافة استثنائية وتجارب مخصصة تلبي تطلعات ضيوفك.",
                            DescriptionEn = "Premium guest services and personalized experiences.",
                            ImageUrl = "/assets/bood-design/images/bood-service-4.jpg",
                            TitleAr = "خدمات الاستقبال والإرشاد المتميزة",
                            TitleEn = "Concierge Excellence"
                        },
                        new
                        {
                            Id = 4,
                            Category = 0,
                            DescriptionAr = "إدارة عمليات الطهي وتقديم الطعام للمطاعم ذات المستوى العالمي.",
                            DescriptionEn = "Culinary operations for world-class restaurants.",
                            ImageUrl = "/assets/bood-design/images/services/hospitality-4.jpg",
                            TitleAr = "إدارة المطاعم الفاخرة",
                            TitleEn = "Fine Dining Management"
                        },
                        new
                        {
                            Id = 5,
                            Category = 0,
                            DescriptionAr = "إدارة هادئة واحترافية لمرافق المنتجعات الصحية الفاخرة.",
                            DescriptionEn = "Tranquil operations for luxury spa facilities.",
                            ImageUrl = "/assets/bood-design/images/services/hospitality-5.jpg",
                            TitleAr = "خدمات المنتجعات الصحية",
                            TitleEn = "Spa & Wellness"
                        },
                        new
                        {
                            Id = 6,
                            Category = 0,
                            DescriptionAr = "إدارة آمنة وفعالة لمركبات الضيوف بأعلى مستويات الاحترافية.",
                            DescriptionEn = "Secure and efficient vehicle management.",
                            ImageUrl = "/assets/bood-design/images/services/hospitality-6.jpg",
                            TitleAr = "خدمات صف السيارات",
                            TitleEn = "Valet & Parking"
                        },
                        new
                        {
                            Id = 7,
                            Category = 1,
                            DescriptionAr = "تعقيم مكثف وشامل للمساحات التجارية والمهنية.",
                            DescriptionEn = "Intensive sanitation for commercial spaces.",
                            ImageUrl = "/assets/bood-design/images/bood-service-2.jpg",
                            TitleAr = "التنظيف العميق",
                            TitleEn = "Deep Cleaning"
                        },
                        new
                        {
                            Id = 8,
                            Category = 1,
                            DescriptionAr = "عناية دورية ومستمرة لضمان بيئة عمل خالية من العيوب.",
                            DescriptionEn = "Routine maintenance for spotless environments.",
                            ImageUrl = "/assets/bood-design/images/services/cleaning-2.jpg",
                            TitleAr = "النظافة اليومية الشاملة",
                            TitleEn = "Daily Janitorial"
                        },
                        new
                        {
                            Id = 9,
                            Category = 1,
                            DescriptionAr = "تنظيف احترافي للزجاج الداخلي والخارجي لضمان رؤية نقية تماماً.",
                            DescriptionEn = "Streak-free exterior and interior glass cleaning.",
                            ImageUrl = "/assets/bood-design/images/services/cleaning-3.jpg",
                            TitleAr = "تنظيف النوافذ والواجهات الزجاجية",
                            TitleEn = "Window & Glass"
                        },
                        new
                        {
                            Id = 10,
                            Category = 1,
                            DescriptionAr = "تنظيف عميق وحماية متطورة للأنسجة والمفروشات.",
                            DescriptionEn = "Deep extraction and fabric protection.",
                            ImageUrl = "/assets/bood-design/images/services/cleaning-4.jpg",
                            TitleAr = "العناية بالسجاد والموكيت",
                            TitleEn = "Carpet Restoration"
                        },
                        new
                        {
                            Id = 11,
                            Category = 1,
                            DescriptionAr = "خدمات تنظيف شاقة مخصصة للمصانع والمستودعات الكبرى.",
                            DescriptionEn = "Heavy-duty cleaning for factories and warehouses.",
                            ImageUrl = "/assets/bood-design/images/services/cleaning-5.jpg",
                            TitleAr = "التعقيم الصناعي",
                            TitleEn = "Industrial Sanitation"
                        },
                        new
                        {
                            Id = 12,
                            Category = 1,
                            DescriptionAr = "إزالة المخلفات والأتربة لتهيئة الموقع بعد أعمال الترميم والبناء.",
                            DescriptionEn = "Removing debris and dust after renovations.",
                            ImageUrl = "/assets/bood-design/images/services/cleaning-6.jpg",
                            TitleAr = "تنظيف ما بعد البناء",
                            TitleEn = "Post-Construction"
                        },
                        new
                        {
                            Id = 13,
                            Category = 2,
                            DescriptionAr = "فحوصات مجدولة لضمان استمرارية العمليات التشغيلية دون انقطاع.",
                            DescriptionEn = "Scheduled checks to ensure uninterrupted operations.",
                            ImageUrl = "/assets/bood-design/images/services/maintenance-1.jpg",
                            TitleAr = "الصيانة الوقائية",
                            TitleEn = "Preventative Maintenance"
                        },
                        new
                        {
                            Id = 14,
                            Category = 2,
                            DescriptionAr = "عناية فائقة بأنظمة التدفئة والتهوية وتكييف الهواء لضمان كفاءتها.",
                            DescriptionEn = "Heating, ventilation, and air conditioning care.",
                            ImageUrl = "/assets/bood-design/images/services/maintenance-2.jpg",
                            TitleAr = "صيانة أنظمة التكييف والتهوية",
                            TitleEn = "HVAC Systems"
                        },
                        new
                        {
                            Id = 15,
                            Category = 2,
                            DescriptionAr = "إدارة آمنة وموثوقة لأنظمة الطاقة والشبكات الكهربائية.",
                            DescriptionEn = "Safe and reliable power system management.",
                            ImageUrl = "/assets/bood-design/images/services/maintenance-3.jpg",
                            TitleAr = "الخدمات الكهربائية",
                            TitleEn = "Electrical Services"
                        },
                        new
                        {
                            Id = 16,
                            Category = 2,
                            DescriptionAr = "صيانة شاملة ومتكاملة لأنظمة المياه والصرف الصحي.",
                            DescriptionEn = "Comprehensive water system maintenance.",
                            ImageUrl = "/assets/bood-design/images/services/maintenance-4.jpg",
                            TitleAr = "حلول السباكة المتقدمة",
                            TitleEn = "Plumbing Solutions"
                        },
                        new
                        {
                            Id = 17,
                            Category = 2,
                            DescriptionAr = "ضمان عمل أنظمة النقل العمودي بأمان وسلاسة مطلقة.",
                            DescriptionEn = "Ensuring safe and smooth vertical transport.",
                            ImageUrl = "/assets/bood-design/images/services/maintenance-5.jpg",
                            TitleAr = "صيانة المصاعد والسلالم الكهربائية",
                            TitleEn = "Elevator Maintenance"
                        },
                        new
                        {
                            Id = 18,
                            Category = 2,
                            DescriptionAr = "استجابة فورية وحلول سريعة للبنية التحتية الحيوية في حالات الطوارئ.",
                            DescriptionEn = "Immediate response for critical infrastructure.",
                            ImageUrl = "/assets/bood-design/images/services/maintenance-6.jpg",
                            TitleAr = "إصلاحات طارئة على مدار الساعة",
                            TitleEn = "24/7 Emergency Repairs"
                        },
                        new
                        {
                            Id = 19,
                            Category = 3,
                            DescriptionAr = "ابتكار مساحات خارجية خلابة ومستدامة تعكس الرقي.",
                            DescriptionEn = "Creating beautiful and sustainable outdoor spaces.",
                            ImageUrl = "/assets/bood-design/images/services/landscaping-1.jpg",
                            TitleAr = "تصميم المناظر الطبيعية",
                            TitleEn = "Landscape Design"
                        },
                        new
                        {
                            Id = 20,
                            Category = 3,
                            DescriptionAr = "جز وتشذيب وتسميد دوري للحفاظ على نضارة المساحات الخضراء.",
                            DescriptionEn = "Regular mowing, trimming, and fertilization.",
                            ImageUrl = "/assets/bood-design/images/services/landscaping-2.jpg",
                            TitleAr = "العناية بالمسطحات الخضراء",
                            TitleEn = "Lawn Care"
                        },
                        new
                        {
                            Id = 21,
                            Category = 3,
                            DescriptionAr = "إدارة فعالة وذكية للمياه للحفاظ على البيئة الطبيعية.",
                            DescriptionEn = "Efficient water management for greenery.",
                            ImageUrl = "/assets/bood-design/images/services/landscaping-3.jpg",
                            TitleAr = "أنظمة الري المتطورة",
                            TitleEn = "Irrigation Systems"
                        },
                        new
                        {
                            Id = 22,
                            Category = 3,
                            DescriptionAr = "إنشاء وتنسيق الممرات، والباحات، والجدران الاستنادية بدقة.",
                            DescriptionEn = "Patios, walkways, and retaining walls.",
                            ImageUrl = "/assets/bood-design/images/services/landscaping-4.jpg",
                            TitleAr = "تنفيذ الأعمال الصلبة في الحدائق",
                            TitleEn = "Hardscaping"
                        },
                        new
                        {
                            Id = 23,
                            Category = 3,
                            DescriptionAr = "تقليم، نقل، وتقييم صحي مستمر للأشجار والنباتات.",
                            DescriptionEn = "Pruning, removal, and health assessments.",
                            ImageUrl = "/assets/bood-design/images/services/landscaping-5.jpg",
                            TitleAr = "العناية بالأشجار والنباتات",
                            TitleEn = "Tree Care"
                        },
                        new
                        {
                            Id = 24,
                            Category = 3,
                            DescriptionAr = "عروض نباتية نابضة بالحياة تتناسب مع جميع فصول السنة.",
                            DescriptionEn = "Vibrant floral displays year-round.",
                            ImageUrl = "/assets/bood-design/images/services/landscaping-6.jpg",
                            TitleAr = "الزراعة الموسمية",
                            TitleEn = "Seasonal Planting"
                        },
                        new
                        {
                            Id = 25,
                            Category = 4,
                            DescriptionAr = "انطباعات أولى احترافية تليق بمستوى أعمالك وشركتك.",
                            DescriptionEn = "Professional first impressions for your business.",
                            ImageUrl = "/assets/bood-design/images/bood-service-5.jpg",
                            TitleAr = "خدمات الاستقبال",
                            TitleEn = "Reception & Front Desk"
                        },
                        new
                        {
                            Id = 26,
                            Category = 4,
                            DescriptionAr = "تعامل فعال ودقيق مع البريد الوارد والصادر لضمان سلاسة العمل.",
                            DescriptionEn = "Efficient handling of incoming and outgoing post.",
                            ImageUrl = "/assets/bood-design/images/services/support-2.jpg",
                            TitleAr = "إدارة غرف البريد",
                            TitleEn = "Mailroom Operations"
                        },
                        new
                        {
                            Id = 27,
                            Category = 4,
                            DescriptionAr = "ضمان سير المهام الإدارية اليومية بكفاءة وانسيابية تامة.",
                            DescriptionEn = "Ensuring smooth day-to-day administrative tasks.",
                            ImageUrl = "/assets/bood-design/images/services/support-3.jpg",
                            TitleAr = "إدارة المكاتب",
                            TitleEn = "Office Management"
                        },
                        new
                        {
                            Id = 28,
                            Category = 4,
                            DescriptionAr = "طاقم أمني مدرب لحماية ممتلكاتك وتأمين منشأتك بفعالية.",
                            DescriptionEn = "Trained guards to protect your assets.",
                            ImageUrl = "/assets/bood-design/images/services/support-4.jpg",
                            TitleAr = "كوادر الحراسة والأمن",
                            TitleEn = "Security Personnel"
                        },
                        new
                        {
                            Id = 29,
                            Category = 4,
                            DescriptionAr = "برامج إبادة آمنة وفعالة لضمان بيئة صحية ونظيفة.",
                            DescriptionEn = "Safe and effective eradication programs.",
                            ImageUrl = "/assets/bood-design/images/services/support-5.jpg",
                            TitleAr = "مكافحة الآفات",
                            TitleEn = "Pest Control"
                        },
                        new
                        {
                            Id = 30,
                            Category = 4,
                            DescriptionAr = "حلول مستدامة وآمنة للتخلص من النفايات وإعادة التدوير.",
                            DescriptionEn = "Sustainable disposal and recycling solutions.",
                            ImageUrl = "/assets/bood-design/images/services/support-6.jpg",
                            TitleAr = "إدارة النفايات وإعادة التدوير",
                            TitleEn = "Waste Management"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
