// <auto-generated />
using Bood.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bood.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Bood.Api.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "$2a$11$ExampleHashPlaceholderForAdmin123",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("Bood.Api.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 0,
                            Description = "Comprehensive management for 5-star properties.",
                            ImageUrl = "/assets/bood-design/images/services/hospitality-1.jpg",
                            Title = "Luxury Hotel Operations"
                        },
                        new
                        {
                            Id = 2,
                            Category = 0,
                            Description = "Seamless execution of high-end events.",
                            ImageUrl = "/assets/bood-design/images/services/hospitality-2.jpg",
                            Title = "Event & Banquet Services"
                        },
                        new
                        {
                            Id = 3,
                            Category = 0,
                            Description = "Premium guest services and personalized experiences.",
                            ImageUrl = "/assets/bood-design/images/services/hospitality-3.jpg",
                            Title = "Concierge Excellence"
                        },
                        new
                        {
                            Id = 4,
                            Category = 0,
                            Description = "Culinary operations for world-class restaurants.",
                            ImageUrl = "/assets/bood-design/images/services/hospitality-4.jpg",
                            Title = "Fine Dining Management"
                        },
                        new
                        {
                            Id = 5,
                            Category = 0,
                            Description = "Tranquil operations for luxury spa facilities.",
                            ImageUrl = "/assets/bood-design/images/services/hospitality-5.jpg",
                            Title = "Spa & Wellness"
                        },
                        new
                        {
                            Id = 6,
                            Category = 0,
                            Description = "Secure and efficient vehicle management.",
                            ImageUrl = "/assets/bood-design/images/services/hospitality-6.jpg",
                            Title = "Valet & Parking"
                        },
                        new
                        {
                            Id = 7,
                            Category = 1,
                            Description = "Intensive sanitation for commercial spaces.",
                            ImageUrl = "/assets/bood-design/images/services/cleaning-1.jpg",
                            Title = "Deep Cleaning"
                        },
                        new
                        {
                            Id = 8,
                            Category = 1,
                            Description = "Routine maintenance for spotless environments.",
                            ImageUrl = "/assets/bood-design/images/services/cleaning-2.jpg",
                            Title = "Daily Janitorial"
                        },
                        new
                        {
                            Id = 9,
                            Category = 1,
                            Description = "Streak-free exterior and interior glass cleaning.",
                            ImageUrl = "/assets/bood-design/images/services/cleaning-3.jpg",
                            Title = "Window & Glass"
                        },
                        new
                        {
                            Id = 10,
                            Category = 1,
                            Description = "Deep extraction and fabric protection.",
                            ImageUrl = "/assets/bood-design/images/services/cleaning-4.jpg",
                            Title = "Carpet Restoration"
                        },
                        new
                        {
                            Id = 11,
                            Category = 1,
                            Description = "Heavy-duty cleaning for factories and warehouses.",
                            ImageUrl = "/assets/bood-design/images/services/cleaning-5.jpg",
                            Title = "Industrial Sanitation"
                        },
                        new
                        {
                            Id = 12,
                            Category = 1,
                            Description = "Removing debris and dust after renovations.",
                            ImageUrl = "/assets/bood-design/images/services/cleaning-6.jpg",
                            Title = "Post-Construction"
                        },
                        new
                        {
                            Id = 13,
                            Category = 2,
                            Description = "Scheduled checks to ensure uninterrupted operations.",
                            ImageUrl = "/assets/bood-design/images/services/maintenance-1.jpg",
                            Title = "Preventative Maintenance"
                        },
                        new
                        {
                            Id = 14,
                            Category = 2,
                            Description = "Heating, ventilation, and air conditioning care.",
                            ImageUrl = "/assets/bood-design/images/services/maintenance-2.jpg",
                            Title = "HVAC Systems"
                        },
                        new
                        {
                            Id = 15,
                            Category = 2,
                            Description = "Safe and reliable power system management.",
                            ImageUrl = "/assets/bood-design/images/services/maintenance-3.jpg",
                            Title = "Electrical Services"
                        },
                        new
                        {
                            Id = 16,
                            Category = 2,
                            Description = "Comprehensive water system maintenance.",
                            ImageUrl = "/assets/bood-design/images/services/maintenance-4.jpg",
                            Title = "Plumbing Solutions"
                        },
                        new
                        {
                            Id = 17,
                            Category = 2,
                            Description = "Ensuring safe and smooth vertical transport.",
                            ImageUrl = "/assets/bood-design/images/services/maintenance-5.jpg",
                            Title = "Elevator Maintenance"
                        },
                        new
                        {
                            Id = 18,
                            Category = 2,
                            Description = "Immediate response for critical infrastructure.",
                            ImageUrl = "/assets/bood-design/images/services/maintenance-6.jpg",
                            Title = "24/7 Emergency Repairs"
                        },
                        new
                        {
                            Id = 19,
                            Category = 3,
                            Description = "Creating beautiful and sustainable outdoor spaces.",
                            ImageUrl = "/assets/bood-design/images/services/landscaping-1.jpg",
                            Title = "Landscape Design"
                        },
                        new
                        {
                            Id = 20,
                            Category = 3,
                            Description = "Regular mowing, trimming, and fertilization.",
                            ImageUrl = "/assets/bood-design/images/services/landscaping-2.jpg",
                            Title = "Lawn Care"
                        },
                        new
                        {
                            Id = 21,
                            Category = 3,
                            Description = "Efficient water management for greenery.",
                            ImageUrl = "/assets/bood-design/images/services/landscaping-3.jpg",
                            Title = "Irrigation Systems"
                        },
                        new
                        {
                            Id = 22,
                            Category = 3,
                            Description = "Patios, walkways, and retaining walls.",
                            ImageUrl = "/assets/bood-design/images/services/landscaping-4.jpg",
                            Title = "Hardscaping"
                        },
                        new
                        {
                            Id = 23,
                            Category = 3,
                            Description = "Pruning, removal, and health assessments.",
                            ImageUrl = "/assets/bood-design/images/services/landscaping-5.jpg",
                            Title = "Tree Care"
                        },
                        new
                        {
                            Id = 24,
                            Category = 3,
                            Description = "Vibrant floral displays year-round.",
                            ImageUrl = "/assets/bood-design/images/services/landscaping-6.jpg",
                            Title = "Seasonal Planting"
                        },
                        new
                        {
                            Id = 25,
                            Category = 4,
                            Description = "Professional first impressions for your business.",
                            ImageUrl = "/assets/bood-design/images/services/support-1.jpg",
                            Title = "Reception & Front Desk"
                        },
                        new
                        {
                            Id = 26,
                            Category = 4,
                            Description = "Efficient handling of incoming and outgoing post.",
                            ImageUrl = "/assets/bood-design/images/services/support-2.jpg",
                            Title = "Mailroom Operations"
                        },
                        new
                        {
                            Id = 27,
                            Category = 4,
                            Description = "Ensuring smooth day-to-day administrative tasks.",
                            ImageUrl = "/assets/bood-design/images/services/support-3.jpg",
                            Title = "Office Management"
                        },
                        new
                        {
                            Id = 28,
                            Category = 4,
                            Description = "Trained guards to protect your assets.",
                            ImageUrl = "/assets/bood-design/images/services/support-4.jpg",
                            Title = "Security Personnel"
                        },
                        new
                        {
                            Id = 29,
                            Category = 4,
                            Description = "Safe and effective eradication programs.",
                            ImageUrl = "/assets/bood-design/images/services/support-5.jpg",
                            Title = "Pest Control"
                        },
                        new
                        {
                            Id = 30,
                            Category = 4,
                            Description = "Sustainable disposal and recycling solutions.",
                            ImageUrl = "/assets/bood-design/images/services/support-6.jpg",
                            Title = "Waste Management"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
